name: RandomDrop
author: Konstantin M.
website: https://github.com/KonstntinM/RandomDrop
description: Leaves a random block instead of the original drop.
main: de.randomdrop.main
version: 1
commands:
  drop:
    description: Reshuffle the Dropped Blocks
